name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest
    name: "Build & Release (MSVC Release)"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure
        run: |
          cmake -B build/release `
            -DCMAKE_CXX_COMPILER=cl `
            -DCMAKE_C_COMPILER=cl `
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build/release --config Release

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/release/Release/vsrun.exe
            build/release/Release/vs-install-dir.exe
          generate_release_notes: true
